### ISSUE TITLE
Comprehensive Notes on Richard Feldmans Front End Masters workshop

### ISSUE THREAD

**Issue by njsfield** [dwyl/learn-elm#78]
At this point in the Readme;
> @TODO: write comprehensive notes on the content in the workshop!

Perhaps a good summary of benefits for taking the course could work well, highlighting;
- Richards thorough teaching of Elm through easy to understand diagrams to help illuminate confusing areas of study.
- Exercises for the learner to tackle building a working github search app as the course progresses, with great explanations of solutions.
- Depth of learning greatly increased by Q & A parts throughout the course; during the course if you have questions they'll likely be raised by the audience in the video themselves, and a lot of time is spent resolving them thoroughly.

**Comment by nelsonic** [comment]
@njsfield having spoken to Richard _extensively_ at Elm Meetup a couple of weeks ago, it's clear to me that the Elm Workshop he made for Front End Masters (FEM) is going be updated in the "_near future_" when Elm 0.19 is released because there are some simplifications resulting in breaking changes. I'd say we should all `continue` to use the videos/notes for our _own_ learning but _wait_ for the next iteration to start doing detailed notes. 
Also, it _pains_ me that the content isn't open/free 
(_i.e. people who cannot afford FEM are locked out..._)

**Comment by newswim** [comment]
I've found that taking notes really helps with my learning, so I've started writing them up. Still need to add screen shots akin to @nelsonic's Transcript for part 1. If anyone else is interested, we could divvy up the work. It takes some time, but I think it's a good investment. Plus, as the [OP](https://github.com/rtfeldman/elm-workshop/issues/8) points out, writing these goes a long way toward making accessible to a larger audience (even if, like you say, this will mostly be for internal use).

Here's what I've done so far:
- [part 4](https://github.com/newswim/elm-workshop/blob/master/part4/Transcript.md) (70% complete)
- [part 5](https://github.com/newswim/elm-workshop/blob/master/part5/Transcript.md) (90% complete)

**Comment by njsfield** [comment]
@nelsonic agreed! @newswim amazing work :) Let's wait until 0.19 then focus on further transcriptions, will be happy to help out 👍

**Comment by newswim** [comment]
My frontend masters subscription ran out, d'oh!

Does anyone have a guess as to when 0.19 will drop?

**Comment by nelsonic** [comment]
@newswim good question. the _only_ person who knows this is Evan.
RF _guessed_ April 2017, but that didn't happen...

**Comment by newswim** [comment]
🤔

If we look at [elm releases], they tend to come (roughly) about once every 6 months. Since the last one happened in November, it's probably a safe guess that it will be "pretty soon".

Here's an [interesting post] where Evan outlines what all is going in 0.19
The [Elm-Dev] google group has been an interesting place to track this discussion!

[elm releases]: https://github.com/elm-lang/elm-compiler/releases
[interesting post]: https://groups.google.com/forum/#!topic/elm-dev/qdu3NqOqGrY
[Elm-Dev]: https://groups.google.com/forum/#!forum/elm-dev

**Comment by nelsonic** [comment]
Closing as no longer relevant.
